import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#fffdf7',
  '--slot4-page-text': '#12324a',
  '--slot4-panel-bg': '#f4fbff',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#58758b',
  '--slot4-soft-muted-text': '#7d95a8',
  '--slot4-accent': '#ff9f1c',
  '--slot4-accent-fill': '#ff7f2a',
  '--slot4-accent-soft': '#fff3cc',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#10263b',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#dfeff7',
  '--slot4-cream': '#fff8df',
  '--slot4-warm': '#fffdf4',
  '--slot4-lavender': '#edf6ff',
  '--slot4-gray': '#f6f8fb',
  '--slot4-body-gradient': 'linear-gradient(180deg,#fffdf6 0%,#f6fbff 42%,#ffffff 100%)',
  '--editable-page-bg': '#fffdf7',
  '--editable-page-text': '#12324a',
  '--editable-container': '1540px',
  '--editable-border': '#d7e6ef',
  '--editable-nav-bg': '#10263b',
  '--editable-nav-text': '#ffffff',
  '--editable-nav-active': '#ffd32d',
  '--editable-nav-active-text': '#10263b',
  '--editable-cta-bg': '#ff7f2a',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#f6f9fc',
  '--editable-footer-text': '#12324a',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent-fill)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[#8d5c00]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_18px_45px_rgba(8,69,148,0.08)]',
  shadowStrong: 'shadow-[0_26px_60px_rgba(8,69,148,0.16)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(16,38,59,0.04),rgba(16,38,59,0.88))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-12 sm:py-14 lg:py-16',
  },
  layout: {
    safeGrid: 'grid gap-5 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-8 lg:grid-cols-[280px_minmax(0,1fr)]',
    rail: 'flex snap-x gap-4 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[220px] shrink-0 snap-start sm:w-[240px]',
  },
  type: {
    eyebrow: 'text-[11px] font-extrabold uppercase tracking-[0.24em] text-[var(--slot4-accent-fill)]',
    heroTitle: 'text-4xl font-extrabold leading-[0.95] tracking-[-0.05em] sm:text-5xl lg:text-[3.4rem]',
    sectionTitle: 'text-3xl font-extrabold tracking-[-0.04em] sm:text-[2.25rem]',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-[1.75rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[1.5rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[1.9rem] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: 'inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-extrabold tracking-[0.01em] text-[var(--slot4-on-accent)] transition duration-200 hover:-translate-y-0.5 hover:brightness-95 active:scale-[0.98]',
    secondary: 'inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-extrabold tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent-fill)] hover:text-[var(--slot4-accent-fill)] active:scale-[0.98]',
    accent: 'inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-extrabold text-[var(--slot4-on-accent)] transition duration-200 hover:-translate-y-0.5 hover:brightness-95 active:scale-[0.98]',
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.4rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_22px_44px_rgba(8,69,148,0.15)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Mix featured, compact, editorial, horizontal, and image-first cards across sections.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
